Create Database
lukman155/Vet-clinic-database pull request #2
Opened 2023-01-25 15:57 UTC by lukman155

* [x]  Create a database named vet_clinic.
* [x]  Create a table named animals with the following columns:
   id: integer
   name: string
   date_of_birth: date
   escape_attempts: integer
   neutered: boolean
   weight_kg: decimal
* [x]   Query to find all animals whose name ends in "mon".
![1-mon-query](https://user-images.githubusercontent.com/109611523/214609400-1c124975-3827-4db6-88ba-71d84e35c53a.png)

 * [x]    Query to List the name of all animals born between 2016 and 2019.
![2-year](https://user-images.githubusercontent.com/109611523/214609485-6e4a2d89-f9c1-495a-bcec-033bae4c6802.png)

 * [x]  Query to list the name of all animals that are neutered and have less than 3 escape attempts.
![3-less](https://user-images.githubusercontent.com/109611523/214609538-14eae72b-2ef3-45ef-ae84-6f55c4dda20b.png)

 * [x]  Query to list the date of birth of all animals named either "Agumon" or "Pikachu".
![4-year](https://user-images.githubusercontent.com/109611523/214609622-e4ac6ba7-cbd1-45ed-90a8-7b26748e768f.png)

 * [x]  Query to list name and escape attempts of animals that weigh more than 10.5kg
![5-name](https://user-images.githubusercontent.com/109611523/214609680-3a015544-03cf-4856-8311-22482534dc3a.png)

 * [x]  Query to find all animals that are neutered.
![6-neuter](https://user-images.githubusercontent.com/109611523/214609752-bec12077-f261-4562-b658-c251923660ab.png)

* [x]  Query to find all animals not named Gabumon.
![7-not](https://user-images.githubusercontent.com/109611523/214609816-c3303e19-9d1d-47f7-9532-7fdd46a36ebd.png)

* [x]  Query to find all animals with a weight between 10.4kg and 17.3kg
![8-within](https://user-images.githubusercontent.com/109611523/214609858-4bab3ea3-37dd-40be-b170-299e0911cf4e.png)

2023-01-25 16:01 UTC, Nemwel-Boniface requested changes
## Hello @lukman155  :wave: ,
I am Nemwel your reviewer for this PR :man_beard: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## :heavy_multiplication_x:  Invalid Code Review Request :heavy_multiplication_x: 

You have submitted a project, that uses the wrong Gitflow. Your project currently merges changes into the main branch, while it is supposed to merge the changes from a feature branch into the dev branch. Kindly make this change.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-26 07:22 UTC, HAMMAS-SALEEM reviewed
# Invalid Submission :red_circle:

## Hey @lukman155 :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following some requirements

Good job on implementing some of the requirements but I cannot proceed review of your pull request because there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-26 07:22 UTC, HAMMAS-SALEEM commented on README.md
> -
- [ ] You have submitted a project, that uses GitHub Flow but you are supposed to use Gitflow. To use Gitflow you follow these rules :arrow_down:
- You make a development branch from the main/master branch :+1:
- Then you make your development branch default :blush:
- At last, whenever you wanna make a change or project, or milestone then you make your feature branch from the development branch and after making that change you would merge that feature branch to development branch :+1:

2023-01-26 07:22 UTC, HAMMAS-SALEEM commented on README.md
> -
- [ ] Your readme file is not descriptive enough :fearful:  Kindly make sure you have all these sections Title, description, Tech Stack, Key Features, Future Features, Getting Started Section, Authors Section, Contribution Section, Acknowledgment Section, Show your support Section, MIT link in your license file :+1:
- [ ] Make sure that all sections should have information and no llink is broken :+1:

2023-01-26 07:39 UTC, closed without merging